jonorthwash/ud-annotatrix

visualise.html
Hello, i've fixed the issue with # comments. Could you merge the request?
=> fixed the issue #18

standalone/annotator.html, standalone/lib/annotator.js
Local version is too old for Bootstrap 4 to be happy. Recommend replacing local version with the version I switched to (so the app works on a boat) but I didn't want to in case that broke other files that depend on it.
=> Stop including jQuery twice - that breaks things

standalone/lib/css/style.css
=> Nicer button spacing

standalone/annotator.html, standalone/lib/annotator.js
=> Fix the table view and make it somewhat pretty

standalone/annotator.html, standalone/lib/annotator.js, standalone/lib/ext/l20n.js, standalone/lib/locales/app.cat.ftl, standalone/lib/locales/app.eng.ftl
workaround for https://bugzilla.mozilla.org/show_bug.cgi?id=897026
=> workaround for chromium not loading "cross origin" resources from file urls

standalone/lib/validation.js, standalone/lib/visualiser.js
Converted https://github.com/coler706/CoNLL-U_cycles to JavaScript and added it to validation.js for dependency cycle check.
Also, any dependency cycle will appear in red.
Example:
For GCI task: https://codein.withgoogle.com/dashboard/task-instances/5433393523195904/
https://codein.withgoogle.com/dashboard/task-instances/6252761614123008/
=> Added dependency cycle check to validation.

standalone/lib/visualiser.js
Added docstrings to visualiser.js.
Not all functions have docstrings (couldn't really figure out what makeEnhancedDependency did because some of the features were broken, also I left out some of the minor functions).
For GCI task: https://codein.withgoogle.com/dashboard/task-instances/4515506667126784/
=> Added docstrings to visualiser.js.

standalone/lib/validation.js, standalone/lib/visualiser.js
Removed old and deprecated is_cyclic code. Cleaned up unecessary code in is_depend_cycles functions, such as removing edge lists because a node can only have one incoming edge. Added comments to some functions.
=> Cleaned up code around checking for cycles

standalone/lib/conllu_table.js
But for loops have to be enabled and there is one error that still comes up, but I couldn't fix.
Mainly whitespace mess fixing and loops modifications.
For GCI task: https://codein.withgoogle.com/dashboard/task-instances/4864259152412672/
=> Make sure JSLint passes on conllu_table.js

standalone/lib/validation.js, standalone/lib/visualiser.js
Does the following checks:
- checks if more than one subject
- checks if more than one obj relation, or there is obj and ccomp.
Marks all of the the conflicting relations as red.
=> Added relation conflict checker.

standalone/lib/validation.js, standalone/lib/visualiser.js
> The subj/obj should have the same parent. Does it work like that?
Fixes this problem in the is_relation_conflict function.
=> Changes such that subj/obj are only problems if same parent.

standalone/lib/gui.js
=> ESC to cancel operation

standalone/lib/gui.js
=> Fixed hint window width

standalone/lib/gui.js
=> Select deprel lebels on edit

standalone/lib/ext/jquery.autocomplete.js
=> Match suggestions at the beginning

standalone/lib/annotator.js, standalone/lib/gui.js
Fixes #217 :)
Pull request also contains changes from my previous PR #210 as it's necessary to work as intended.
@ftyers
=> Prevent tab from unfocusing edit box

standalone/lib/annotator.js, standalone/lib/gui.js
=> Fixed deprel selection when in edit mode

standalone/lib/visualiser.js
Fixes #200
@JPJPJPOPOP /cc
@ftyers /cc
=> Calculate actual word width

standalone/annotator.html, standalone/lib/annotator.js
Fixes #19.
Before uploading:
After uploading:
=> Added upload button and progress bar for upload.

standalone/lib/annotator.js
=> Fixed textarea rows

standalone/lib/annotator.js
Reverts jonorthwash/ud-annotatrix#223
=> Revert "Fixed textarea rows"

standalone/annotator.html, standalone/export.html, standalone/lib/gui.js, standalone/lib/visualiser.js
@ftyers 
It exports to PNG by default :)
=> Fixes some errors with export.

standalone/annotator.html, standalone/lib/annotator.js
=> Remove upload and append functionality.

standalone/lib/annotator.js
Reverts jonorthwash/ud-annotatrix#234
=> Revert "Revert "Fixed textarea rows""

standalone/lib/visualiser.js
Fixes #167 
Hard to find the cause, but easy to fix!
The vertical graphs are somewhat ugly, but they already were before they got broken.
=> Vertical graphs are now working

standalone/lib/visualiser.js
@ftyers 
Fixes #200 and #247 (as #242 doesn't work)
=> Fixed problem with overlapping

client/gui/table.js, server/public/js/bundle.js
Fixes #326 
The problem was so simple to solve yet such a pain to figure out
=> Fix table view deleting words

client/graph/index.js
=> Fix deprel offset when changing to rtl.

client/graph/visualiser.js
Fixes #349.
Also, some small style changes.
=> Style changes and change to token numbers.

client/graph/visualiser.js, client/utils/export.js, server/public/css/style.css
Token numbers and border get bolded when form is root.
=> Style changes to token number.

client/graph/visualiser.js, client/gui/keyboard.js
- Forms are closer together.
- 0 : center and fit to window
- +/= : zoom in
- -/_ : zoom out
=> Changes to style and key shortcuts.

notatrix/.babelrc, notatrix/gulpfile.babel.js, notatrix/package-lock.json, notatrix/package.json
Found a few more random bits that were broken ..
I'm going to open this as a PR for visibility, but merge it immediately.  Lmk if you would prefer direct commits in the future!
=> Fix broken notatrix build
